### ISSUE TITLE
C\user\.virtualenvs\Fastapi_tortoise-F_kfWYDa\lib\site-packages\casbin\core_enforcer.py:203: RuntimeWarning: coroutine 'TortoiseAdapter.load_policy' was never awaited   self.adapter.load_policy(new_model) RuntimeWarning: Enable tracemalloc to get the object allocation traceback

### ISSUE THREAD

**Issue by RicarTang** [thearchitector/casbin-tortoise-adapter#5]
```
def load_policy(self):
        """reloads the policy from file/database."""
        need_to_rebuild = False
        new_model = copy.deepcopy(self.model)
        new_model.clear_policy()

        try:

            self.adapter.load_policy(new_model)

            new_model.sort_policies_by_subject_hierarchy()

            new_model.sort_policies_by_priority()

            new_model.print_policy()

            if self.auto_build_role_links:

                need_to_rebuild = True
                for rm in self.rm_map.values():
                    rm.clear()

                new_model.build_role_links(self.rm_map)

            self.model = new_model
```
self.adapter.load_policy(new_model)casbin does not call with await. What should I do?

**Comment by hsluoyz** [comment]
@thearchitector

**Comment by thearchitector** [comment]
@RicarTang this package uses `asynccasbin`, which is installed as a dependency. based on that traceback, it looks like it's trying to use plain old `casbin`, which definitely won't work (since yes, it's missing all the asyncio stuff).

it seems like there might there be a namespace conflict here? try uninstalling `casbin` and the error should resolve... unfortunately there isn't much I can do to prevent the conflict as both the async and sync packages are installed under `import casbin`, which is a bit silly imo.

`pip uninstall casbin` or with whatever manager you're using. you just can't have both installed at the same time

**Comment by RicarTang** [comment]
> @RicarTang this package uses `asynccasbin`, which is installed as a dependency. based on that traceback, it looks like it's trying to use plain old `casbin`, which definitely won't work (since yes, it's missing all the asyncio stuff).
> 
> it seems like there might there be a namespace conflict here? try uninstalling `casbin` and the error should resolve... unfortunately there isn't much I can do to prevent the conflict as both the async and sync packages are installed under `import casbin`, which is a bit silly imo.
> 
> `pip uninstall casbin` or with whatever manager you're using. you just can't have both installed at the same time

Okay, thank you
